Repository REmemory-team/REmemory-Nodejs, pull requests merged in 2024-01, with the labels that each got.

#2 [FEAT] User, Pcapsule, Rcapsule 기본 API 구현
  .gitignore
  babel.config.js
  config/dbConfig.js
  config/error.js
  config/expressConfig.js
  config/response.js
  config/responseStatus.js
  config/swaggerConfig.js
  config/tokenAuthMiddleware.js
  index.js
  package-lock.json
  package.json
  src/app/Pcapsule/pcapsuleController.js
  src/app/Pcapsule/pcapsuleDao.js
  src/app/Pcapsule/pcapsuleProvider.js
  src/app/Pcapsule/pcapsuleRoute.js
  src/app/Pcapsule/pcapsuleService.js
  src/app/Rcapsule/rcapsuleController.js
  src/app/Rcapsule/rcapsuleDao.js
  src/app/Rcapsule/rcapsuleProvider.js
  src/app/Rcapsule/rcapsuleRoute.js
  src/app/Rcapsule/rcapsuleService.js
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userRoute.js
  src/app/User/userService.js
  src/app/User/userSql.js
  src/app/temp
Labels: :sparkles: feat

#4 feat: pcapsule status 상태변경 api 구현
  config/scheduler.js
  index.js
  src/app/Pcapsule/pcapsuleController.js
  src/app/Pcapsule/pcapsuleDao.js
  src/app/Pcapsule/pcapsuleProvider.js
  src/app/Pcapsule/pcapsuleRoute.js
  src/app/Pcapsule/pcapsuleService.js
Labels: :sparkles: feat

#5 [FEAT] user 상태변경 api 구현
  config/responseStatus.js
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
  src/app/User/userService.js
  src/app/User/userSql.js
Labels: :sparkles: feat

#8 [CI] ci/cd 파이프라인 구축
  .github/workflows/dev_deploy.yml
  .platform/nginx/nginx.conf
  Procfile
  config/responseStatus.js
  config/scheduler.js
  index.js
  package-lock.json
  package.json
  src/app/Health/healthController.js
  src/app/Health/healthRoute.js
  src/app/Pcapsule/pcapsuleController.js
  src/app/Rcapsule/rcapsuleController.js
  webpack.config.js
Labels: :sparkles: feat, :construction_worker: ci

#10 ♻️ [REFACTOR] webpack.config 파일 변경
  webpack.config.cjs
Labels: :recycle: refactor

#18 [FEAT] Rcapsule 음성 메세지 추가 API구현
  config/aws.js
  config/multer.js
  package-lock.json
  package.json
  src/app/Pcapsule/pcapsuleRoute.js
  src/app/Rcapsule/rcapsuleController.js
  src/app/Rcapsule/rcapsuleDao.js
  src/app/Rcapsule/rcapsuleRoute.js
  src/app/Rcapsule/rcapsuleService.js
Labels: :sparkles: feat

#23 [FEAT] Rcapsule URL 접속 시 화면, 롤페 API 구현
  config/multer.js
  package-lock.json
  package.json
  src/app/rcapsule/rcapsuleController.js
  src/app/rcapsule/rcapsuleDao.js
  src/app/rcapsule/rcapsuleProvider.js
  src/app/rcapsule/rcapsuleRouter.js
  src/app/rcapsule/rcapsuleService.js
Labels: :sparkles: feat

#26 🐛[FIX] es6 관련 오류 해결
  .eslintrc.js
  babel.config.js
  babel.config.json
  package.json
  webpack.config.js
Labels: :bug: bug, :construction_worker: ci

#31 🐛 [FIX] webpack.config.js entry 경로 변경
  webpack.config.js
Labels: :bug: bug, :construction_worker: ci

#32 [FIX] webpack.config.js 경로 원래대로 변경
  webpack.config.js
Labels: :bug: bug, :construction_worker: ci
