Repository REmemory-team/REmemory-Nodejs, pull requests merged in 2024-03, with the labels that each got.

#121 기본 작업
  config/scheduler.js
  src/app/Capsule/capsuleController.js
  src/app/Capsule/capsuleDao.js
  src/app/Capsule/capsuleProvider.js
  src/app/Capsule/capsuleRoute.js
Labels: :memo: docs

#122 capsule_code
  config/scheduler.js
  src/app/Capsule/capsuleController.js
  src/app/Capsule/capsuleDao.js
  src/app/Capsule/capsuleProvider.js
  src/app/Capsule/capsuleRoute.js
  swagger/rememorySwagger.yaml
Labels: :memo: docs

#123 feat: 카카오 알림톡 구현 예제
  config/kakaoAlramTalk.js
Labels: :sparkles: feat

#125 ♻️ Refactor: userId 테스트용 값으로 고정
  src/app/Pcapsule/pcapsuleController.js
  src/app/Rcapsule/rcapsuleController.js
Labels: :recycle: refactor

#126 ♻️ Refactor: rcapsuleController.js test용 userId 고정
  src/app/Rcapsule/rcapsuleController.js
Labels: :recycle: refactor

#127 ♻️ Refactor: tokenAuthMiddleware 주석처리
  src/app/Pcapsule/pcapsuleRoute.js
Labels: :recycle: refactor

#128 ♻️ Refactor: rcapsuleRoute.js tokenAuthMiddleware 주석처리
  src/app/Rcapsule/rcapsuleRoute.js
Labels: :recycle: refactor

#129 Feat: db health check 추가
  src/app/Health/healthController.js
  src/app/Health/healthRoute.js
Labels: :sparkles: feat

#130 Refactor: healthController.js import 구문 추가
  src/app/Health/healthController.js
Labels: :recycle: refactor

#131 Refactor: capsule test용 userId 값으로 고정
  src/app/Capsule/capsuleController.js
  src/app/Capsule/capsuleDao.js
  src/app/Capsule/capsuleRoute.js
Labels: :recycle: refactor

#136 Test: rcapsule 생성 에러 테스트
  src/app/Rcapsule/rcapsuleDao.js
Labels: :bug: bug

#139 Fix: rcapsule 생성 애러 문제
  src/app/Rcapsule/rcapsuleController.js
  src/app/Rcapsule/rcapsuleDao.js
  src/app/Rcapsule/rcapsuleService.js
Labels: :bug: bug

#141 ♻️ [Refactor/113] 롤링페이퍼 작성된 편지 개수 전달, 당일 오픈 기능
  .github/workflows/actions.yml
  config/responseStatus.js
  src/app/Pcapsule/pcapsuleDao.js
  src/app/Pcapsule/pcapsuleService.js
  src/app/Rcapsule/rcapsuleDao.js
  src/app/Rcapsule/rcapsuleService.js
Labels: :recycle: refactor
