Repository REmemory-team/REmemory-Nodejs, pull requests merged in 2024-02, with the labels that each got.

#36 pcapsule_create succes
  config/dbConfig.js
  src/app/Pcapsule/pcapsuleController.js
  src/app/Pcapsule/pcapsuleDao.js
  src/app/Pcapsule/pcapsuleProvider.js
  src/app/Pcapsule/pcapsuleService.js
  swagger/rememorySwagger.yaml
Labels: :sparkles: feat

#37 create 에러핸들링(db 정상 정보 생성)
  src/app/Pcapsule/pcapsuleDao.js
  src/app/Pcapsule/pcapsuleService.js
Labels: :sparkles: feat

#38 패스워드 저장, 조회까지 완료
  src/app/Pcapsule/pcapsuleDao.js
  src/app/Pcapsule/pcapsuleProvider.js
  src/app/Pcapsule/pcapsuleRoute.js
  src/app/Pcapsule/pcapsuleService.js
  swagger/rememorySwagger.yaml
Labels: :sparkles: feat

#39 pcapsule swagger test 완료
  src/app/Pcapsule/pcapsuleDao.js
  src/app/Pcapsule/pcapsuleService.js
  swagger/rememorySwagger.yaml
Labels: :sparkles: feat

#45 [Refactor] path variable로 변경, swagger 추가
  config/responseStatus.js
  src/app/User/userController.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
  src/app/User/userService.js
  swagger/rememorySwagger.yaml
Labels: :recycle: refactor

#47 ci: docker 추가
  .dockerignore
  .github/workflows/actions.yml
  .github/workflows/dev_deploy.yml
  Dockerfile
Labels: :construction_worker: ci

#48 [Fix] scripts 수정
  package.json
Labels: :bug: bug, :construction_worker: ci

#50 Rcapsule 코드 리팩토링
  config/multer.js
  config/responseStatus.js
  src/app/Pcapsule/pcapsuleService.js
  src/app/Rcapsule/rcapsuleController.js
  src/app/Rcapsule/rcapsuleDao.js
  src/app/Rcapsule/rcapsuleProvider.js
  src/app/Rcapsule/rcapsuleRoute.js
  src/app/Rcapsule/rcapsuleService.js
  src/app/User/userDao.js
  swagger/rememorySwagger.yaml
Labels: :recycle: refactor

#51 ♻️ [Refactor] pcapsule 생성, 조회, 상세조회 로직 변경
  config/responseStatus.js
  src/app/Pcapsule/pcapsuleController.js
  src/app/Pcapsule/pcapsuleDao.js
  src/app/Pcapsule/pcapsuleProvider.js
  src/app/Pcapsule/pcapsuleService.js
  src/app/Rcapsule/rcapsuleService.js
  swagger/rememorySwagger.yaml
Labels: :memo: docs, :recycle: refactor

#53 ♻️ [Refactor] pcapsule 글사진, 음성 API 구현 및 수정
  src/app/Pcapsule/pcapsuleController.js
  src/app/Pcapsule/pcapsuleDao.js
  src/app/Pcapsule/pcapsuleProvider.js
  src/app/Pcapsule/pcapsuleRoute.js
  src/app/Pcapsule/pcapsuleService.js
  src/app/Rcapsule/rcapsuleRoute.js
  swagger/rememorySwagger.yaml
Labels: :memo: docs, :sparkles: feat, :recycle: refactor

#55 ♻️ [Refactor] pcapsule 생성 API 수정
  src/app/Pcapsule/pcapsuleController.js
  src/app/Pcapsule/pcapsuleDao.js
  src/app/Pcapsule/pcapsuleService.js
  swagger/rememorySwagger.yaml
Labels: :memo: docs, :recycle: refactor

#57 ✨ [Feat] rcapsule 조회 API 구현
  src/app/Pcapsule/pcapsuleService.js
  src/app/Rcapsule/rcapsuleController.js
  src/app/Rcapsule/rcapsuleDao.js
  src/app/Rcapsule/rcapsuleRoute.js
  src/app/Rcapsule/rcapsuleService.js
  swagger/rememorySwagger.yaml
Labels: :memo: docs, :sparkles: feat, :recycle: refactor

#64 ♻️ [Refactor] pcapsule 글사진 API 로직 수정 및 이미지 업로드 함수 구현
  config/multer.js
  src/app/Pcapsule/pcapsuleProvider.js
  src/app/Pcapsule/pcapsuleService.js
  swagger/rememorySwagger.yaml
Labels: :memo: docs, :sparkles: feat, :recycle: refactor

#66 ♻️ [Refactor] 캡슐 상태변경 코드 수정
  config/scheduler.js
  index.js
  src/app/Capsule/capsuleDao.js
  src/app/Capsule/capsuleProvider.js
  src/app/Pcapsule/pcapsuleDao.js
  src/app/Pcapsule/pcapsuleProvider.js
Labels: :recycle: refactor

#67 ♻️ [Refactor] rcapsule/create/text_image API
  src/app/Rcapsule/rcapsuleController.js
  src/app/Rcapsule/rcapsuleDao.js
  src/app/Rcapsule/rcapsuleRoute.js
  src/app/Rcapsule/rcapsuleService.js
  swagger/rememorySwagger.yaml
Labels: :recycle: refactor

#69 ✨[Feat] Capsule 알림메일 구현 완료
  config/nodemailer.js
  config/scheduler.js
  package-lock.json
  package.json
  src/app/Capsule/capsuleDao.js
  src/app/Capsule/capsuleProvider.js
  src/app/Rcapsule/rcapsuleRoute.js
  src/app/Rcapsule/rcapsuleService.js
Labels: :sparkles: feat

#72 ✨ [Feat] rcapsule 상세조회 API 구현
  src/app/Capsule/capsuleController.js
  src/app/Rcapsule/rcapsuleController.js
  src/app/Rcapsule/rcapsuleDao.js
  src/app/Rcapsule/rcapsuleService.js
Labels: :sparkles: feat

#79 [Refactor] Rcapsule 생성 시 에러 핸들링 수정
  src/app/Rcapsule/rcapsuleController.js
  src/app/Rcapsule/rcapsuleService.js
Labels: :recycle: refactor

#82 Fix: tokenAuthMiddleware rcapsule/create router에 추가
  config/swaggerConfig.js
  src/app/Rcapsule/rcapsuleRoute.js
Labels: :bug: bug

#90 ♻️ [Refactor] 프론트 요청에 따라 rcapsuleUrl 변경
  src/app/Pcapsule/pcapsuleRoute.js
  src/app/Rcapsule/rcapsuleService.js
Labels: :recycle: refactor

#92 ♻️ [Refactor] pcapsule create api 수정
  src/app/Pcapsule/pcapsuleController.js
  src/app/Pcapsule/pcapsuleRoute.js
  swagger/rememorySwagger.yaml
Labels: :memo: docs, :recycle: refactor

#94 ♻️ [Refactor] rcapsule rcapsuleUrl 수정
  src/app/Rcapsule/rcapsuleService.js
Labels: :recycle: refactor

#99 [Feat] Rcapsule url_info 예외처리 추가
  config/responseStatus.js
  src/app/Rcapsule/rcapsuleController.js
  src/app/Rcapsule/rcapsuleDao.js
  src/app/Rcapsule/rcapsuleService.js
Labels: :sparkles: feat, :recycle: refactor

#100 [Refactor] capsule/retrieve/detail rcapsule response dear_name 추가
  src/app/Rcapsule/rcapsuleController.js
  src/app/Rcapsule/rcapsuleDao.js
  src/app/Rcapsule/rcapsuleService.js
Labels: :recycle: refactor

#113 [Refactor] 요청 데이터 크기 제한 1mb에서 5mb로 수정
  config/expressConfig.js
Labels: :recycle: refactor

#115 🐛 [Fix] pcapsule 음성 관련 에러 수정
  config/swaggerConfig.js
  src/app/Pcapsule/pcapsuleService.js
Labels: :bug: bug

#116 🐛 [Fix] pcapsule 음성 관련 에러 수정
  src/app/Pcapsule/pcapsuleService.js
Labels: :bug: bug
